### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by JW-vfx** [Theo-SAMINADIN-td/NukeDepthCrafter#15]
Hi
I followed your installation steps, but get the following error:
![image_2024-12-09_154423000](https://github.com/user-attachments/assets/cb0820ec-d419-49bd-be7f-82f51124277e)

NukeX 15.1v4, 64 bit, built Oct 30 2024.
Copyright (c) 2024 The Foundry Visionmongers Ltd.  All Rights Reserved.

Traceback (most recent call last):
  File "C:/Users/Johan/.nuke/menu.py", line 1, in <module>
    from nukedc import CreateDCNode, UpdatePath, GenerateDepth
  File "C:\Program Files\Nuke15.1v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/Johan/.nuke\nukedc.py", line 4, in <module>
    import torch
  File "C:\Program Files\Nuke15.1v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python310\Lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\Johan\AppData\Local\Programs\Python\Python310\Lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

Attached is my menu.py and init.py files as well.
![image](https://github.com/user-attachments/assets/9b0dd6dc-4efb-43a8-837a-82145530a4fc)
![image](https://github.com/user-attachments/assets/6ca1da85-dc5b-424e-83e5-6d7585390714)

Any help would be greatly appreciated as this tool is amazing!
Thankyou

**Comment by Theo-SAMINADIN-td** [comment]
Hi @JW-vfx, could you share your environment installed packages with `pip list` please ? 🙏

**Comment by DeBontDigital** [comment]
Hi @Theo-SAMINADIN-td ,

I've got the exact same issue, here is my pip list:
`
Package            Version
------------------ -----------
accelerate         0.30.1
certifi            2024.12.14
charset-normalizer 3.4.0
colorama           0.4.6
contourpy          1.3.1
cycler             0.12.1
diffusers          0.29.1
filelock           3.13.1
fonttools          4.55.3
fsspec             2024.10.0
huggingface-hub    0.27.0
idna               3.10
importlib_metadata 8.5.0
Jinja2             3.1.3
kiwisolver         1.4.7
MarkupSafe         2.1.5
matplotlib         3.8.4
mpmath             1.3.0
mypy-extensions    1.0.0
networkx           3.2.1
numpy              1.26.3
opencv-python      4.8.1.78
packaging          24.2
pillow             11.0.0
pip                22.3.1
psutil             6.1.0
pyparsing          3.2.0
pyre-extensions    0.0.29
python-dateutil    2.9.0.post0
PyYAML             6.0.2
regex              2024.11.6
requests           2.32.3
safetensors        0.4.5
setuptools         65.5.0
six                1.17.0
sympy              1.13.1
tokenizers         0.19.1
torch              2.0.1+cu118
tqdm               4.67.1
transformers       4.41.2
typing_extensions  4.9.0
typing-inspect     0.9.0
urllib3            2.2.3
xformers           0.0.20
zipp               3.21.0`

**Comment by JW-vfx** [comment]
Hi
Here is my pip list

C:\Users\Johan>pip list
Package            Version
------------------ -----------
accelerate         0.30.1
certifi            2024.8.30
charset-normalizer 3.4.0
colorama           0.4.6
contourpy          1.3.1
cycler             0.12.1
diffusers          0.29.1
filelock           3.13.1
fonttools          4.55.0
fsspec             2024.10.0
huggingface-hub    0.26.2
idna               3.10
importlib_metadata 8.5.0
Jinja2             3.1.3
kiwisolver         1.4.7
MarkupSafe         2.1.5
matplotlib         3.8.4
mpmath             1.3.0
mypy-extensions    1.0.0
networkx           3.2.1
numpy              1.26.3
opencv-python      4.8.1.78
packaging          24.2
pillow             11.0.0
pip                24.3.1
psutil             6.1.0
pyparsing          3.2.0
pyre-extensions    0.0.29
python-dateutil    2.9.0.post0
PyYAML             6.0.2
regex              2024.11.6
requests           2.32.3
safetensors        0.4.5
setuptools         65.5.0
six                1.16.0
sympy              1.13.1
tokenizers         0.19.1
torch              2.0.1+cu118
tqdm               4.67.0
transformers       4.41.2
typing_extensions  4.9.0
typing-inspect     0.9.0
urllib3            2.2.3
xformers           0.0.20
zipp               3.21.0

**Comment by SashaMelentev** [comment]
Hi! I have one issue too.

ModuleNotFoundError: No module named 'torch'

![image](https://github.com/user-attachments/assets/0ef0bdb1-16af-4cdc-85c8-9a92355b752c)

**Comment by MaikiOS** [comment]
очередной шедевр который работает только на cuda 11.8 , боже в чем сложность писать на 12,4 . столько гемороя из-за этого .

**Comment by jemabaris** [comment]
I've got the same issues as everybody else here. Been trying to solve this for hours now but I'm not exactly good at python so any help would be much appreciated. 
![WindowsTerminal_1wroZeEOE6](https://github.com/user-attachments/assets/46180bf5-0afb-4353-b594-08a085141cf2)

**Comment by Isoide** [comment]
Hey,
We're having a simillar issue but with the c10_cuda.dll

![Image](https://github.com/user-attachments/assets/0086b773-e3ba-406e-ad9a-8faf959b033f)

I have tried a little bit further, with copying dlls found in Nuke directory and overwriting torch dlls in Python310 directory, then the nuke opening proceeded a bit further and brought this. 
OSError: [WinError 127] The specified procedure could not be found. Error loading "c:\users/mzarzycki/appdata/local/programs/python/python310/lib/site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

I am guessing this might be due to different versions of torch in different nuke versions.
For instance 15.0 (v6) had PyTorch 1.12.1, and on 15.1 you can find PyTorch 2.2.1

As soon as I overwritten the dlls with nuke's dlls then it worked and so my guess would be to find nvfuser_codegen.dll or the whole torch version compatible with current version of nuke.

But then the rest of the dependiencies like torchvision, torchaudio or xformers might get out of sync. Hopefully this might help with troubleshooting or narrowing down the problem.

EDIT:
Oh, the pip list btw:

Package                   Version
------------------------- -----------
accelerate                0.30.1
alembic                   1.13.3
annotated-types           0.7.0
anyio                     4.6.0
astroid                   3.3.6
asttokens                 2.4.1
async-timeout             4.0.3
attrs                     23.2.0
backcall                  0.2.0
backports.tarfile         1.2.0
beautifulsoup4            4.12.3
bidict                    0.23.1
bleach                    6.1.0
blinker                   1.7.0
build                     1.2.2
cachetools                5.3.2
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
cmake                     3.31.2
colorama                  0.4.6
contourpy                 1.2.0
cycler                    0.12.1
decorator                 5.1.1
defusedxml                0.7.1
diffusers                 0.29.1
dill                      0.3.9
docopt                    0.6.2
docutils                  0.21.2
et-xmlfile                1.1.0
exceptiongroup            1.2.2
executing                 2.0.1
fastapi                   0.115.0
fastjsonschema            2.19.1
ffmpeg                    1.4
filelock                  3.13.1
Fileseq                   2.1.1
Flask                     3.0.2
fonttools                 4.50.0
fsspec                    2024.3.0
google-api-core           2.17.1
google-api-python-client  2.118.0
google-auth               2.27.0
google-auth-httplib2      0.2.0
googleapis-common-protos  1.62.0
greenlet                  3.1.1
gunicorn                  23.0.0
h11                       0.14.0
httpcore                  1.0.5
httplib2                  0.22.0
httpx                     0.27.2
huggingface-hub           0.27.1
idna                      3.6
imageio                   2.34.0
importlib_metadata        8.5.0
ipython                   8.12.3
isort                     5.13.2
itsdangerous              2.1.2
jaraco.classes            3.4.0
jaraco.context            6.0.1
jaraco.functools          4.1.0
jedi                      0.19.1
Jinja2                    3.1.3
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.2
jupyter_core              5.7.2
jupyterlab_pygments       0.3.0
keyring                   25.4.1
kiwisolver                1.4.5
lazy_loader               0.4
loguru                    0.6.0
Mako                      1.3.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.4
matplotlib-inline         0.1.7
mccabe                    0.7.0
mdurl                     0.1.2
mistune                   3.0.2
more-itertools            10.5.0
mpmath                    1.3.0
multipledispatch          1.0.0
mypy-extensions           1.0.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
networkx                  3.2.1
nh3                       0.2.18
notify_py                 0.3.43
numpy                     1.26.3
opencolorio               2.4.1
opencv-python             4.8.1.78
openpyxl                  3.1.2
OpenTimelineIO            0.15.0
packaging                 24.0
pandocfilters             1.5.1
parso                     0.8.4
pickleshare               0.7.5
pillow                    10.2.0
pip                       24.2
pipdeptree                2.16.2
pipreqs                   0.5.0
pkginfo                   1.10.0
platformdirs              4.2.2
prompt-toolkit            3.0.43
protobuf                  4.25.2
psutil                    5.9.8
pure-eval                 0.2.2
pyaaf2                    1.6.0
pyasn1                    0.5.1
pyasn1-modules            0.3.0
pyassimp                  5.2.5
pydantic                  2.9.2
pydantic_core             2.23.4
Pygments                  2.18.0
pylint                    3.3.2
PyOpenGL                  3.1.7
pyparsing                 3.1.1
pyproject_hooks           1.2.0
PyQt5                     5.15.10
PyQt5-Qt5                 5.15.2
PyQt5_sip                 12.16.1
pyre-extensions           0.0.29
pyrr                      0.10.3
python-dateutil           2.9.0.post0
python-engineio           4.9.1
python-multipart          0.0.12
python-socketio           5.11.4
pytube                    15.0.0
pywin32                   306
pywin32-ctypes            0.2.3
PyYAML                    6.0.2
pyzmq                     26.0.3
readme_renderer           44.0
redis                     5.1.0
referencing               0.35.1
reflex                    0.6.0
reflex-chakra             0.6.0
reflex-hosting-cli        0.1.13
regex                     2024.11.6
requests                  2.31.0
requests-toolbelt         1.0.0
rfc3986                   2.0.0
rich                      13.8.1
rpds-py                   0.18.1
rsa                       4.9
safetensors               0.5.2
schedule                  1.2.1
scikit-image              0.22.0
scipy                     1.10.1
setuptools                70.1.1
sgtk                      0.21.7
shellingham               1.5.4
shotgun_api3              3.5.1
simple-websocket          1.0.0
six                       1.16.0
sniffio                   1.3.1
soupsieve                 2.5
SQLAlchemy                2.0.35
sqlmodel                  0.0.22
stack-data                0.6.3
starlette                 0.38.6
starlette-admin           0.14.1
sympy                     1.13.1
tabulate                  0.9.0
tifffile                  2024.2.12
tinycss2                  1.3.0
tokenizers                0.19.1
toml                      0.10.2
tomli                     2.0.1
tomlkit                   0.13.2
torch                     2.0.1+cu118
tornado                   6.4
tqdm                      4.66.2
traitlets                 5.14.3
transformers              4.41.2
trimesh                   4.2.0
twine                     5.1.1
typer                     0.12.5
typing_extensions         4.10.0
typing-inspect            0.9.0
uritemplate               4.1.1
urllib3                   2.2.0
uvicorn                   0.31.0
wcwidth                   0.2.13
webencodings              0.5.1
websockets                13.1
Werkzeug                  3.0.2
wheel                     0.44.0
win32-setctime            1.1.0
winshell                  0.6
wrapt                     1.16.0
wsproto                   1.2.0
xformers                  0.0.20
yarg                      0.1.9
zipp                      3.20.2

**Comment by Nkk-pixel** [comment]
> Hi! I have one issue too.
> 
> ModuleNotFoundError: No module named 'torch'
> 
> ![image](https://github.com/user-attachments/assets/0ef0bdb1-16af-4cdc-85c8-9a92355b752c)

I might know a sollution! In your init.py find this line: 
#nuke.pluginAddPath(r"path/to/your/PATH/site-packages")
And REMOVE the hashtag, to enable the line. 
I might be wrong but it seems nuke is trying to find site-packages in default path. Not the custom one.

**Comment by SouthAngel** [comment]
I got error  
![Image](https://github.com/user-attachments/assets/3055449c-a772-42c9-977c-5b7b37764d2f)
when i run  pip install torch==2.0.1+cu118 --index-url https://download.pytorch.org/whl/cu118

Could you give some help with me?

**Comment by LukemanX** [comment]
> Could you give some help with me?

Are you running the specified python version? That is 3.10.10 if I'm not mistaken.

I first had an issue trying to run the whole thing in 3.12, after switching to 3.10.10 it got fixed and could find the required package version.

**Comment by LukemanX** [comment]
Hi.

I am still getting the same errors described above when trying to run Nuke (15.0v4).

Upon closer inspection, some packages differ from the ones listed in previous replies, despite following the same installation procedure, which bas basically copy pasting from the Github install guide.

torch and cuda seem to be the correct versions. tried several times with the same results.

Could someone whose installation is working please share their pip list, Nuke version, and init.py general paths configuration to check if something is off for us who are having issues? Thanks!


Here's my pip list and below the Nuke error:

accelerate     0.30.1
certifi            2022.12.7
charset-normalizer 2.1.1
colorama           0.4.6
contourpy          1.3.1
cycler             0.12.1
diffusers          0.29.1
filelock           3.13.1
fonttools          4.57.0
fsspec             2025.3.2
huggingface-hub    0.30.2
idna               3.4
importlib_metadata 8.6.1
Jinja2             3.1.3
kiwisolver         1.4.8
MarkupSafe         2.1.5
matplotlib         3.8.4
mpmath             1.3.0
mypy-extensions    1.0.0
networkx           3.3
numpy              1.26.3
opencv-python      4.8.1.78
packaging          24.2
pillow             11.0.0
pip                22.3.1
psutil             7.0.0
pyparsing          3.2.3
pyre-extensions    0.0.29
python-dateutil    2.9.0.post0
PyYAML             6.0.2
regex              2024.11.6
requests           2.28.1
safetensors        0.5.3
setuptools         65.5.0
six                1.17.0
sympy              1.13.1
tokenizers         0.19.1
torch              2.0.1+cu118
tqdm               4.67.1
transformers       4.41.2
typing_extensions  4.9.0
typing-inspect     0.9.0
urllib3            1.26.13
xformers           0.0.20
zipp               3.21.0



NukeX 15.0v4, 64 bit, built Feb  6 2024.
Copyright (c) 2024 The Foundry Visionmongers Ltd.  All Rights Reserved.

Traceback (most recent call last):
  File "C:/Users/Admin/.nuke/menu.py", line 1, in <module>
    from nukedc import CreateDCNode, UpdatePath, GenerateDepth
  File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/Admin/.nuke\nukedc.py", line 4, in <module>
    import torch
  File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\python_venv\nukeDepthCrafter\Lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\python_venv\nukeDepthCrafter\Lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

**Comment by lumiafonso** [comment]
Same issue with me!

import torch
  File "C:\Users/lumil/AppData/Local/Programs/Python/Python310/Lib/site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users/lumil/AppData/Local/Programs/Python/Python310/Lib/site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

**Comment by Isoide** [comment]
Hey

I've found the solution while reworking our inhouse solutions.

Instead of using external python, use the python found under Nuke installation, then when running pip installs add --target to a external path that would be in sys.path

This way you ensure the libraries are compiled with proper Python and therefore you don't rely on specific python version, but use python version compiled by nuke.

It worked for Nuke15.1v5 and Nuke16.0v6
