### ISSUE TITLE
input tensor must fit into 32-bit index math

### ISSUE THREAD

**Issue by arlo-ml** [Theo-SAMINADIN-td/NukeDepthCrafter#6]
Hi, 
I've been experimenting with longer sequences (1944 frames) using the Model mode, and I receive this error message:

RuntimeError: input tensor must fit into 32-bit index math

Is there a maximum number of frames accepted by the plugin?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users/admin/.nuke\nukedc.py", line 88, in GenerateDepthAction
    depthcrafter_demo.infer(
  File "C:\Users/admin/.nuke\DepthCrafterPlugin\utils.py", line 81, in infer
    res = self.pipe(
  File "D:\Temp/DepthCrafterPlugin2/Lib/site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users/admin/.nuke\DepthCrafterPlugin\depthcrafter\depth_crafter_ppl.py", line 158, in __call__
    video_embeddings = self.encode_video(
  File "D:\Temp/DepthCrafterPlugin2/Lib/site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users/admin/.nuke\DepthCrafterPlugin\depthcrafter\depth_crafter_ppl.py", line 32, in encode_video
    video_224 = _resize_with_antialiasing(video.float(), (224, 224))
  File "D:\Temp/DepthCrafterPlugin2/Lib/site-packages\diffusers\pipelines\stable_video_diffusion\pipeline_stable_video_diffusion.py", line 645, in _resize_with_antialiasing
    input = _gaussian_blur2d(input, ks, sigmas)
  File "D:\Temp/DepthCrafterPlugin2/Lib/site-packages\diffusers\pipelines\stable_video_diffusion\pipeline_stable_video_diffusion.py", line 723, in _gaussian_blur2d
    out_x = _filter2d(input, kernel_x[..., None, :])
  File "D:\Temp/DepthCrafterPlugin2/Lib/site-packages\diffusers\pipelines\stable_video_diffusion\pipeline_stable_video_diffusion.py", line 684, in _filter2d
    input = torch.nn.functional.pad(input, padding_shape, mode="reflect")
RuntimeError: input tensor must fit into 32-bit index math

**Comment by Theo-SAMINADIN-td** [comment]
Hi @arlo-ml, There is no real frames limitation. It depends on the resolution of the input, the number of frames to process, the CPU Offload option and the VRAM available. 

Depending on your VRAM, It could be possible to process a "higher" resolution or longer sequences by switching from **model**, to **sequencial**.
